apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend
        image: 734842486567.dkr.ecr.us-east-2.amazonaws.com/ludx-frontend:latest
        ports:
        - containerPort: 80