name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <region>

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <account-id>.dkr.ecr.<region>.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t <ecr-repo-url>:latest .
          docker push <ecr-repo-url>:latest

      - name: Update kubeconfig
        run: aws eks --region <region> update-kubeconfig --name my-cluster

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/frontend-service.yaml
          kubectl apply -f k8s/frontend-deployment.yaml